### ISSUE TITLE
Luna架构改变

### ISSUE THREAD

**Issue by ibuler** [jumpserver/luna#10]
1. Luna只负责前端内容(现在仅负责terminal前端)，后端api调用jms api，后端ws调用coco

2. Luna 职责：
  - terminal连接，包含两种，1.直接点击左侧hostname连接 2.进入交互式模式连接(类似coco)
  - terminal实时监控，由于coco分布式，所以可能需要连接到不同的coco上
  - terminal分享，多人共享一个session，多读多写 【低优先级】

**Comment by liuzheng** [comment]
@wojiushixiaobai 刚出0.5-alpha-1，还没来得及写docs，你想知道啥

**Comment by wojiushixiaobai** [comment]
@liuzheng  

 luna 目录ng i 报错，所以上来看看，结果讨论的都是旧版本。。就回了一句。。
正在努力找原因 ing。

**Comment by liuzheng** [comment]
@wojiushixiaobai 啥问题

**Comment by wojiushixiaobai** [comment]
@liuzheng 

ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/assets/inspinia/style.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/opt/luna/node_modules/node-sass/vendor'
at Object.fs.readdirSync (fs.js:924:18)
at Object.getInstalledBinaries (/opt/luna/node_modules/node-sass/lib/extensions.js:128:13)
at foundBinariesList (/opt/luna/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/opt/luna/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/opt/luna/node_modules/node-sass/lib/errors.js:45:5)
at module.exports (/opt/luna/node_modules/node-sass/lib/binding.js:15:30)
at Object. (/opt/luna/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (module.js:660:30)
at Object.Module._extensions..js (module.js:671:10)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Module.require (module.js:604:17)
at require (internal/module.js:11:18)
at Object. (/opt/luna/node_modules/sass-loader/lib/loader.js:3:14)
at Module._compile (module.js:660:30)
at Object.Module._extensions..js (module.js:671:10)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Module.require (module.js:604:17)
at require (internal/module.js:11:18)
@ ./src/assets/inspinia/style.scss 4:14-204
@ multi ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.css ./node_modules/xterm/dist/xterm.css ./node_modules/layui-layer/dist/theme/default/layer.css ./node_modules/animate.css/animate.min.css ./src/assets/inspinia/style.scss ./src/styles.css

**Comment by liuzheng** [comment]
@wojiushixiaobai  npm rebuild node-sass
